name: Production deploy Diskont Admin

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TARGET_FOLDER: "/home/front/Discont-admin"

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        source: "."
        target: "${{ env.TARGET_FOLDER }}"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        script_stop: true
        script: |
          git --work-tree="${{ env.TARGET_FOLDER }}" --git-dir="${{ env.TARGET_FOLDER }}/.git" clean -f .
          node --version
          /usr/share/yarn/bin/yarn --cwd "${{ env.TARGET_FOLDER }}"
          /usr/share/yarn/bin/yarn --cwd "${{ env.TARGET_FOLDER }}" run build
          pm2 reload admin.diskont.uz
          sh /home/devops/deploy.sh "${{ github.event.head_commit.message }}" "admin.diskont.uz deploy"
